version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "michael-mpj"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@react-three/*"
          - "@testing-library/*"
      build-tools:
        patterns:
          - "vite*"
          - "rollup*"
          - "babel*"
          - "webpack*"
      linting-tools:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"

  - package-ecosystem: "npm"
    directory: "/packages/r3f-components"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "r3f-components"

  - package-ecosystem: "npm"
    directory: "/projects/R3f-StarterKit"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "starter-kit"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    assignees:
      - "michael-mpj"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
      
