name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: |
          yarn
          yarn prettier . --write
      - uses: autofix-ci/action@v5
        with:
          commit-message: "Apply Prettier format"
