name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Create GitHub Release (placeholder)
        run: echo "Add publish steps (npm publish, gh release) as needed."
