name: Stale
on:
  schedule:
    - cron: "0 0 * * 1" # weekly
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/stale@v10
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity."
          days-before-stale: 60
          days-before-close: 7
